# config.py

import sys

# ===== Steering =====
STEERING_INVERT = True
STEERING_DEAD_ZONE = 0.03

SERVO_CENTER_US = 1600
SERVO_LEFT_US   = 950
SERVO_RIGHT_US  = 2200


# ===== Throttle =====
THROTTLE_INVERT = True        
THROTTLE_DEAD_ZONE = 0.05

THROTTLE_NEUTRAL_US = 1600
THROTTLE_FORWARD_US = 1900
THROTTLE_REVERSE_US = 1100


# ===== Input =====
KEYBOARD_ENABLED = sys.stdin.isatty()
GAMEPAD_ENABLED = True

GAMEPAD_DEVICE = "/dev/input/event5"  # DualShock 4

# Клавиши безопасности
KEYBOARD_ARM_KEY = "enter"
KEYBOARD_DISARM_KEY = "esc"

STEERING_GAIN = 1.8   # 1.5–2.5 обычно идеально

# ===== Auto cruise speed scaling =====
# Slow down when turning and/or when obstacles are close ahead.
AUTO_TURN_STEER_THRESHOLD = 0.35
AUTO_TURN_SPEED_SCALE = 0.65
AUTO_TURN_STEER_VALUE = 0.60
AUTO_TURN_MANUAL_OVERRIDE = 0.15
AUTO_TURN_RAMP_PER_SEC = 2.0

# Limit steering at higher speeds (AUTO only)
AUTO_STEER_SPEED_LOW = 0.10
AUTO_STEER_SPEED_HIGH = 0.35
AUTO_STEER_MAX_LOW = 1.00
AUTO_STEER_MAX_HIGH = 0.50

AUTO_OBS_CENTER_THRESHOLD = 0.35
AUTO_CLOSEST_THRESHOLD = 0.75
AUTO_OBS_SPEED_SCALE = 0.50

# ===== Vision snapshots =====
SNAPSHOT_ENABLED = True
SNAPSHOT_IMAGES = True
SNAPSHOT_IMAGE_W = 320
SNAPSHOT_IMAGE_H = 240
SNAPSHOT_IMAGE_MAX_FPS = 5.0
SNAPSHOT_ON_STOP_DECISION = True
SNAPSHOT_ON_TURN_DECISION = False

# ===== Turn decision =====
TURN_CENTER_THRESHOLD = 0.35
TURN_DIFF_THRESHOLD = 0.08
